// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://paayjqwfaxhjholtblrm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhYXlqcXdmYXhoamhvbHRibHJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDIxNjcsImV4cCI6MjA2NTQ3ODE2N30.lIRgJtLxDIKVKr0ygFZj1CMw-rbmQVw58FHvCISUUyM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);